name: Build aarch64

on:
  workflow_dispatch:

env:
    # Use docker.io for Docker Hub if empty
    REGISTRY: ghcr.io
    # github.repository as <account>/<repo>
    IMAGE_NAME: "${{ github.repository }}-alpine-aarch64"
  
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:    
      contents: write   
      packages: write   
      # This is used    to complete the identity challenge
      # with sigstore   /fulcio when running outside of PRs.
      id-token: write   
    strategy:
      matrix:
        include:
        - platform: linux/arm64
          arch: aarch64

    steps:
    - uses: actions/checkout@v3
    - name: Install system dependencies
      run: sudo apt-get install -y tree
    - name: Set up QEMU
      if: matrix.platform != 'linux/amd64'
      uses: docker/setup-qemu-action@v2
      with:
        platforms: ${{ matrix.platform }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build packages (${{ matrix.platform }})
      uses: docker/build-push-action@v6
      with:
        platforms: ${{matrix.platform}}
        context: ./alpine
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ env.IMAGE_NAME}}